name: "DS Pro Tokens Release"
description: "Connect with DS Pro and release your tokens"
author: "DS Pro"
inputs:
  release_branch:
    description: "The branch that contains the tokens to be released. Defaults to main."
    required: false
    default: "main"
  tokens_path:
    description: "The repository path where the tokens.json can be found."
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
