name: 'Semantic Release Action'
description: 'GitHub Action for semantic-release with dist folder publishing'
inputs:
  dist-dir:
    description: 'Path to the dist directory to be published'
    required: true
    default: './dist'
  release-branch:
    description: 'The branch where a release will be created. Defaults to "main".'
    required: true
    default: '"main"'
  dry-run:
    description: 'Whether to perform a dry run (no changes are made)'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token'
    required: true
  node-auth-token:
    description: 'Node.js auth token'
    required: true
  registry-url:
    description: 'Registry URL where the dist directory will be published. Defaults to "https://npm.pkg.github.com".'
    required: false
    default: 'https://npm.pkg.github.com'

runs:
    using: composite
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: ${{ inputs.registry-url }}
          node-version: "20.x"

      - name: Import Configuration files
        shell: bash
        run: |
          npm install -g @semantic-release/changelog@6.0.3 @semantic-release/commit-analyzer@13.0.0 @semantic-release/git@10.0.1 @semantic-release/github@11.0.0 @semantic-release/release-notes-generator@14.0.1 semantic-release@24.1.2
          cp $GITHUB_ACTION_PATH/template.release.config.js ./release.config.js

      - name: Replace dist directory placeholder
        shell: bash
        run: |
          sed -i 's|{{DIST_DIR}}|${{ inputs.dist-dir }}|g' ./release.config.js
          sed -i 's|{{RELEASE_BRANCH}}|${{ inputs.release-branch }}|g' ./release.config.js

      - name: Perform release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
          NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
        run: |
          if [ "${{ inputs.dry-run }}" = "true" ]; then
            npx semantic-release --dry-run
          else
            npx semantic-release
          fi

branding:
  icon: 'package'
  color: 'green'
