name: 'Semantic Release Action'
description: 'GitHub Action for semantic-release with dist folder publishing'
inputs:
  dist-dir:
    description: 'Path to the dist directory to be published'
    required: true
    default: './dist'
  dry-run:
    description: 'Whether to perform a dry run (no changes are made)'
    required: false
    default: 'false'
  github_token:
    description: 'GitHub token'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --build-arg
    - DIST_DIR=${{ inputs.dist-dir }}
  env:
    DRY_RUN: ${{ inputs.dry-run }}
    GITHUB_TOKEN: ${{ inputs.github_token }}

branding:
  icon: 'package'
  color: 'green'
