name: 'Semantic Release Action'
description: 'GitHub Action for semantic-release with dist folder publishing'
inputs:
  dist-dir:
    description: 'Path to the dist directory to be published'
    required: true
    default: './dist'
  dry-run:
    description: 'Whether to perform a dry run (no changes are made)'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Import Configuration files
      shell: bash
      run: |
        cp $GITHUB_ACTION_PATH/package.json ./
        cp $GITHUB_ACTION_PATH/template.release.config.js ./release.config.js

    - name: Replace dist directory path
      shell: bash
      run: |
        sed -i "s|{{dist-dir}}|${{ inputs.dist-dir }}|g" ./release.config.js

    - name: Find the version of Node from package.json
      id: node-version
      shell: bash
      run: echo "version=$(jq -r .engines.node ./package.json)" >> $GITHUB_OUTPUT

    - run: echo ${{ steps.node-version.outputs.version }}
      shell: bash

    - name: Install Node
      uses: actions/setup-node@v4.0.4
      with:
        node-version: ${{ steps.node-version.outputs.version }}
        check-latest: true

    - name: Install npm package
      shell: bash
      run: npm install

    - name: Perform release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        PUBLISH_COMMAND: ${{ inputs.publish-command }}
        ASSETS_PATH: ${{ inputs.assets-path }}
      run: |
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          npx semantic-release --dry-run
        else
          npx semantic-release
        fi

branding:
  icon: 'package'
  color: 'green'
