name: Release DS Pro Tokens

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  pull-requests: write

jobs:
  integrate-tokens:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - shell: bash
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@Design-System-Pro"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - shell: bash
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
