name: Release DS Pro Tokens

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  integrate-tokens:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - shell: bash
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "pnpm"

      - shell: bash
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Run DS Pro Token Integration Action
        uses: ./
        with:
          tokens_path: "example"
